apiVersion: v1
kind: Service
metadata:
  labels:
    app: crossdns
    component: crossdns
  name: crossdns
  namespace: lmxia
spec:
  ports:
    - name: udp
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: crossdns
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossdns
  namespace: lmxia
  labels:
    app: crossdns
spec:
  selector:
    matchLabels:
      app: crossdns
  template:
    metadata:
      labels:
        app: crossdns
    spec:
      containers:
        - name: crossdns
          image: lmxia/crossdns:v1
          env:
      serviceAccount: syncer
      serviceAccountName: syncer
